<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <ProjectReference Include="../../src/TradeBlotter.Framework/TradeBlotter.Framework.csproj" />
    <ProjectReference Include="../../src/TradeBlotter.Framework.WinAppDriver/TradeBlotter.Framework.WinAppDriver.csproj" />
  </ItemGroup>
</Project>
