<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <ReqnrollUseIntermediateOutputPathForCodeBehind>true</ReqnrollUseIntermediateOutputPathForCodeBehind>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
    <ProjectReference Include="../../src/TradeBlotter.Framework.WinAppDriver/TradeBlotter.Framework.WinAppDriver.csproj" />
    <ProjectReference Include="../../src/TradeBlotter.Screenplay/TradeBlotter.Screenplay.csproj" />
    <ProjectReference Include="../../src/TradeBlotter.Sut/TradeBlotter.Sut.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Target Name="CopyDesktopSut" AfterTargets="Build">
    <ItemGroup>
      <DesktopSut Include="../../src/TradeBlotter.Sut/bin/$(Configuration)/net9.0-windows/*" />
    </ItemGroup>
    <Copy SourceFiles="@(DesktopSut)" DestinationFolder="$(OutDir)sut" SkipUnchangedFiles="true" />
  </Target>
</Project>
